name: sysped

services:
  db:
    image: mysql:8.0
    container_name: sysped-db
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33066:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  app:
    build: .
    container_name: sysped-app
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8085:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-sysped
    restart: on-failure
    depends_on:
      - app
    env_file:
      - .env
    command: tunnel run
    networks:
      - default

volumes:
  db_data:

networks:
  default:
    driver: bridge